### ISSUE TITLE
Request for information : page break in a cell

### ISSUE THREAD

**Issue by vincentb1** [olpa/tex#6]
Not a bug, just begging for more vision about `cals` evolution.

I am currently seeking a solution to generate long table LaTeX code. The `longtable` package has a limitation that in comination with `multirow`, if the `multirow`content is taller than the set of other rows, it will spill out. 

So I am looking at alternatives, like `cals`, and I am also trying to know more about `htmltabs` by @patrickschulz.

Also, currently, to my knowledge, no LaTeX package allows pagebreaks in the middle of a very tall cell (maybe `htmltabs` does that, I don't know as this package is not yet published).   However in [tb101parashchenko.pdf](http://mirrors.ctan.org/macros/latex/contrib/cals/tb101parashchenko.pdf) §2.8.3 Inter-row page breaks, you suggest that some evolution of `cals` is possible. I would like to know whether this is something you are considering to bring in near future …

**Comment by olpa** [comment]
I was overoptimistic. Now I think that the task (page breaks inside the cells) is impossible.

My best attempt is here:

- https://gist.github.com/olpa/2a7096b231d0dbe2b022122b1674b4ff
- plus few links from here http://uucode.com/blog/2019/03/03/multi-page-table-with-inter-row-page-breaks/

Depending on the reason for long tables, you may want to look at speedata publisher from Patrick Gundlach: https://www.speedata.de/en/. It's a mix of TeX core and a lot of Lua scripts.

**Comment by vincentb1** [comment]
Thank you for the feedback.

**Comment by fsoedjede** [comment]
Hello @vincentb1, back then, did you find a way to do the automatic page break in cells?
If yes, could you share?
Have you tried speedata? I'm interested in an example if you have been able to do it

Thanks
